name:  Posting test plans.

on:
  issue_comment:
    branches: [ master]
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  COMMENT_STRING: ${{ github.event.comment.body }}
  EVENT_TYPE: ${{ github.event.action }}

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Display the path
      run: |
         if [[ "$COMMENT_STRING" == *"screenshot:"* ]];
          then
            echo "Started generating screenshots.."
          elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]
          then
            echo "Started fetching test plans..."
            exit 0
          else
            echo "No action performed."
            exit 0
          fi
        shell: bash
