name: Swift
on:
  pull_request:
    branches: [ main ]
jobs:
  linking_check:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building
      run: swift build -v
    - name: Running Danger Swift
      uses: danger/swift@2.0.3
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
