name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [feature/* ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Available Simulators
      run: instruments -s devices
    - name: Build
      run: pwd
   # - name: Take Screenshots
     # run: ./script.swift
