name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [feature/* ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Available Simulators
     # run: xcrun simctl list --json -v
    - name: Take Screenshots
      run: ./script.swift
