name:  Generate Screenshots

on:
  issue_comment:
    branches: [feature/*, main ]
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  COMMENT_STRING: ${{ github.event.comment.body }}
  EVENT_TYPE: ${{ github.event.action }}

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Display the path
      run: |
        if [[ "$COMMENT_STRING" == *"screenshot:"* ]];
        then
          echo "Started generating screenshots.."
        else
          echo "No action performed."
          exit 1
        fi
      shell: bash
    - uses: actions/checkout@v2
    #- name: Available Simulators
     # run: xcrun simctl list --json -v
    - name: Take Screenshots
      run: ./script.swift screenshot
    - name: change directory
      run: cd screenshots
    - name: Archive screenshot to artifact
      uses: actions/upload-artifact@v2
      with:
        name: Screenshots
        path: screenshots/*
  
  Download_Artifact:
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      id: download
      with:
        name: Screenshots
        path: screenshots
    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
    
  UploadScreenshotsToS3:
    name: Uplaod screenshots to S3 bucket
    needs: build
    #needs: Download_Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        id: download
        with:
          name: Screenshots
          path: screenshots
      - name: upload to S3
        uses: RandhirMSingh/S3Manager@main
        id: s3Images
        with:
          args: --acl public-read
        env:
          FILE:  ${{steps.download.outputs.download-path}}
          AWS_REGION: 'ap-south-1'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: ${{ secrets.S3_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: print body
        run: echo ${{steps.s3Images.outputs}}
 
